/*
 *  BOSCH REXROTH
 *
 *  Copyright (c) Bosch Rexroth AG 2014
 *  Internet: http://www.boschrexroth.com
 *
 *  Product Name:   NYCe4000
 *  Component Name: support
 *  Subsystem Name: deh
 *
 *  THIS FILE IS AUTOMATICALLY GENERATED BY
 *  generate_enum_conversion.py
 *  MANUAL MODIFICATIONS WILL BE OVERWRITTEN!!!
 */
/**
 *  @file
 *  @brief  Enum conversion functions for deh.
 *  
 *  For every enum in the deh subsystem the following type to string conversion functions exist:
 *  - "<TYPE>ToString(TYPE)"            Convert the given value of "<TYPE>" to its exact string representation.
 *  - "<TYPE>ToUserString(TYPE)"        Convert the given value of "<TYPE>" to a human readable string.
 *  - "<TYPE>ToDescription(TYPE)"       Convert the given value of "<TYPE>" to a descriptive string.
 *  - "<TYPE>FromString(string, TYPE)"  Convert the given string to value of "<TYPE>".
 *  - "<TYPE>IsValid(TYPE)"             Checks if the given value of "<TYPE>" is valid.
 */

#ifndef __DEHENUMS_H__
#define __DEHENUMS_H__

#include "dehapi.h"

#ifndef DEH_EXPORT
    #ifdef WIN32
        #define DEH_EXPORT __declspec(dllimport)
    #else
        #define DEH_EXPORT
    #endif
#endif

#ifdef __cplusplus
extern "C" {
#endif
/**
 *  @addtogroup deh_conversion
 *  @{
 */

//  DEH_LOG_TYPE Conversion routines

/**
 *  @brief      Convert type DEH_LOG_TYPE to the exact string representation.
 *
 *  @param[in]  value   The value to convert.
 *
 *  @return     The string representation of value.
 */
DEH_EXPORT const char* NYCE_API DehLogTypeToString(DEH_LOG_TYPE value);

/**
 *  @brief      Convert type DEH_LOG_TYPE to a human readable string.
 *
 *  @param[in]  value   The value to convert.
 *
 *  @return     The human readable string representation of value.
 */
DEH_EXPORT const char* NYCE_API DehLogTypeToUserString(DEH_LOG_TYPE value);

/**
 *  @brief      Convert type DEH_LOG_TYPE to a descriptive string.
 *
 *  @param[in]  value   The value to convert.
 *
 *  @return     The description of value.
 */
DEH_EXPORT const char* NYCE_API DehLogTypeToDescription(DEH_LOG_TYPE value);

/**
 *  @brief      Convert the given string to an DEH_LOG_TYPE.
 *
 *  @param[in]  string  The string to convert.
 *  @param[out] pValue  The enum value of string.
 *
 *  @retval     NYCE_OK                     string is successfully converted to a valid DEH_LOG_TYPE.
 *  @retval     DEH_ERR_INVALID_PARAMETER   string or pValue is NULL.
 *  @retval     DEH_ERR_UNKNOWN_ENUM_STRING string could not be converted to DEH_LOG_TYPE.
 */
DEH_EXPORT NYCE_STATUS NYCE_API DehLogTypeFromString(const char* string, DEH_LOG_TYPE* pValue);

/**
 *  @brief      Check if value is a valid DEH_LOG_TYPE.
 *
 *  @param[in]  value   The value to check.
 *
 *  @retval     TRUE    value is a valid DEH_LOG_TYPE.
 *  @retval     FALSE   value is not a valid DEH_LOG_TYPE.
 */
DEH_EXPORT BOOL DehLogTypeIsValid(DEH_LOG_TYPE value);


/**
 *  @}
 */
#ifdef __cplusplus
}
#endif

#endif
