/*
 *  BOSCH REXROTH
 *
 *  Copyright (c) Bosch Rexroth AG 2014
 *  Internet: http://www.boschrexroth.com
 *
 *  Product Name:   NYCe4000
 *  Component Name: support
 *  Subsystem Name: deh
 *
 *  THIS FILE IS AUTOMATICALLY GENERATED BY
 *  generate_enum_conversion.py
 *  MANUAL MODIFICATIONS WILL BE OVERWRITTEN!!!
 */
/**
 *  @file
 *  @brief  Enum conversion functions for sacfcl.
 *  
 *  For every enum in the sacfcl subsystem the following type to string conversion functions exist:
 *  - "<TYPE>ToString(TYPE)"            Convert the given value of "<TYPE>" to its exact string representation.
 *  - "<TYPE>ToUserString(TYPE)"        Convert the given value of "<TYPE>" to a human readable string.
 *  - "<TYPE>ToDescription(TYPE)"       Convert the given value of "<TYPE>" to a descriptive string.
 *  - "<TYPE>FromString(string, TYPE)"  Convert the given string to value of "<TYPE>".
 *  - "<TYPE>IsValid(TYPE)"             Checks if the given value of "<TYPE>" is valid.
 */

#ifndef __SACFCLENUMS_H__
#define __SACFCLENUMS_H__

#include "sacfclapi.h"

#ifndef DEH_EXPORT
    #ifdef WIN32
        #define DEH_EXPORT __declspec(dllimport)
    #else
        #define DEH_EXPORT
    #endif
#endif

#ifdef __cplusplus
extern "C" {
#endif
/**
 *  @addtogroup sacfcl_conversion
 *  @{
 */

//  SAC_FCL_SENSOR_ID Conversion routines

/**
 *  @brief      Convert type SAC_FCL_SENSOR_ID to the exact string representation.
 *
 *  @param[in]  value   The value to convert.
 *
 *  @return     The string representation of value.
 */
DEH_EXPORT const char* NYCE_API SacFclSensorIdToString(SAC_FCL_SENSOR_ID value);

/**
 *  @brief      Convert type SAC_FCL_SENSOR_ID to a human readable string.
 *
 *  @param[in]  value   The value to convert.
 *
 *  @return     The human readable string representation of value.
 */
DEH_EXPORT const char* NYCE_API SacFclSensorIdToUserString(SAC_FCL_SENSOR_ID value);

/**
 *  @brief      Convert type SAC_FCL_SENSOR_ID to a descriptive string.
 *
 *  @param[in]  value   The value to convert.
 *
 *  @return     The description of value.
 */
DEH_EXPORT const char* NYCE_API SacFclSensorIdToDescription(SAC_FCL_SENSOR_ID value);

/**
 *  @brief      Convert the given string to an SAC_FCL_SENSOR_ID.
 *
 *  @param[in]  string  The string to convert.
 *  @param[out] pValue  The enum value of string.
 *
 *  @retval     NYCE_OK                     string is successfully converted to a valid SAC_FCL_SENSOR_ID.
 *  @retval     SAC_ERR_INVALID_PARAMETER   string or pValue is NULL.
 *  @retval     SAC_ERR_UNKNOWN_ENUM_STRING string could not be converted to SAC_FCL_SENSOR_ID.
 */
DEH_EXPORT NYCE_STATUS NYCE_API SacFclSensorIdFromString(const char* string, SAC_FCL_SENSOR_ID* pValue);

/**
 *  @brief      Check if value is a valid SAC_FCL_SENSOR_ID.
 *
 *  @param[in]  value   The value to check.
 *
 *  @retval     TRUE    value is a valid SAC_FCL_SENSOR_ID.
 *  @retval     FALSE   value is not a valid SAC_FCL_SENSOR_ID.
 */
DEH_EXPORT BOOL SacFclSensorIdIsValid(SAC_FCL_SENSOR_ID value);


//  SAC_FCL_DIAG_DATA_ID Conversion routines

/**
 *  @brief      Convert type SAC_FCL_DIAG_DATA_ID to the exact string representation.
 *
 *  @param[in]  value   The value to convert.
 *
 *  @return     The string representation of value.
 */
DEH_EXPORT const char* NYCE_API SacFclDiagDataIdToString(SAC_FCL_DIAG_DATA_ID value);

/**
 *  @brief      Convert type SAC_FCL_DIAG_DATA_ID to a human readable string.
 *
 *  @param[in]  value   The value to convert.
 *
 *  @return     The human readable string representation of value.
 */
DEH_EXPORT const char* NYCE_API SacFclDiagDataIdToUserString(SAC_FCL_DIAG_DATA_ID value);

/**
 *  @brief      Convert type SAC_FCL_DIAG_DATA_ID to a descriptive string.
 *
 *  @param[in]  value   The value to convert.
 *
 *  @return     The description of value.
 */
DEH_EXPORT const char* NYCE_API SacFclDiagDataIdToDescription(SAC_FCL_DIAG_DATA_ID value);

/**
 *  @brief      Convert the given string to an SAC_FCL_DIAG_DATA_ID.
 *
 *  @param[in]  string  The string to convert.
 *  @param[out] pValue  The enum value of string.
 *
 *  @retval     NYCE_OK                     string is successfully converted to a valid SAC_FCL_DIAG_DATA_ID.
 *  @retval     SAC_ERR_INVALID_PARAMETER   string or pValue is NULL.
 *  @retval     SAC_ERR_UNKNOWN_ENUM_STRING string could not be converted to SAC_FCL_DIAG_DATA_ID.
 */
DEH_EXPORT NYCE_STATUS NYCE_API SacFclDiagDataIdFromString(const char* string, SAC_FCL_DIAG_DATA_ID* pValue);

/**
 *  @brief      Check if value is a valid SAC_FCL_DIAG_DATA_ID.
 *
 *  @param[in]  value   The value to check.
 *
 *  @retval     TRUE    value is a valid SAC_FCL_DIAG_DATA_ID.
 *  @retval     FALSE   value is not a valid SAC_FCL_DIAG_DATA_ID.
 */
DEH_EXPORT BOOL SacFclDiagDataIdIsValid(SAC_FCL_DIAG_DATA_ID value);


//  SAC_FCL_STATE Conversion routines

/**
 *  @brief      Convert type SAC_FCL_STATE to the exact string representation.
 *
 *  @param[in]  value   The value to convert.
 *
 *  @return     The string representation of value.
 */
DEH_EXPORT const char* NYCE_API SacFclStateToString(SAC_FCL_STATE value);

/**
 *  @brief      Convert type SAC_FCL_STATE to a human readable string.
 *
 *  @param[in]  value   The value to convert.
 *
 *  @return     The human readable string representation of value.
 */
DEH_EXPORT const char* NYCE_API SacFclStateToUserString(SAC_FCL_STATE value);

/**
 *  @brief      Convert type SAC_FCL_STATE to a descriptive string.
 *
 *  @param[in]  value   The value to convert.
 *
 *  @return     The description of value.
 */
DEH_EXPORT const char* NYCE_API SacFclStateToDescription(SAC_FCL_STATE value);

/**
 *  @brief      Convert the given string to an SAC_FCL_STATE.
 *
 *  @param[in]  string  The string to convert.
 *  @param[out] pValue  The enum value of string.
 *
 *  @retval     NYCE_OK                     string is successfully converted to a valid SAC_FCL_STATE.
 *  @retval     SAC_ERR_INVALID_PARAMETER   string or pValue is NULL.
 *  @retval     SAC_ERR_UNKNOWN_ENUM_STRING string could not be converted to SAC_FCL_STATE.
 */
DEH_EXPORT NYCE_STATUS NYCE_API SacFclStateFromString(const char* string, SAC_FCL_STATE* pValue);

/**
 *  @brief      Check if value is a valid SAC_FCL_STATE.
 *
 *  @param[in]  value   The value to check.
 *
 *  @retval     TRUE    value is a valid SAC_FCL_STATE.
 *  @retval     FALSE   value is not a valid SAC_FCL_STATE.
 */
DEH_EXPORT BOOL SacFclStateIsValid(SAC_FCL_STATE value);


//  SAC_FCL_SENSOR_SOURCE_TYPE Conversion routines

/**
 *  @brief      Convert type SAC_FCL_SENSOR_SOURCE_TYPE to the exact string representation.
 *
 *  @param[in]  value   The value to convert.
 *
 *  @return     The string representation of value.
 */
DEH_EXPORT const char* NYCE_API SacFclSensorSourceTypeToString(SAC_FCL_SENSOR_SOURCE_TYPE value);

/**
 *  @brief      Convert type SAC_FCL_SENSOR_SOURCE_TYPE to a human readable string.
 *
 *  @param[in]  value   The value to convert.
 *
 *  @return     The human readable string representation of value.
 */
DEH_EXPORT const char* NYCE_API SacFclSensorSourceTypeToUserString(SAC_FCL_SENSOR_SOURCE_TYPE value);

/**
 *  @brief      Convert type SAC_FCL_SENSOR_SOURCE_TYPE to a descriptive string.
 *
 *  @param[in]  value   The value to convert.
 *
 *  @return     The description of value.
 */
DEH_EXPORT const char* NYCE_API SacFclSensorSourceTypeToDescription(SAC_FCL_SENSOR_SOURCE_TYPE value);

/**
 *  @brief      Convert the given string to an SAC_FCL_SENSOR_SOURCE_TYPE.
 *
 *  @param[in]  string  The string to convert.
 *  @param[out] pValue  The enum value of string.
 *
 *  @retval     NYCE_OK                     string is successfully converted to a valid SAC_FCL_SENSOR_SOURCE_TYPE.
 *  @retval     SAC_ERR_INVALID_PARAMETER   string or pValue is NULL.
 *  @retval     SAC_ERR_UNKNOWN_ENUM_STRING string could not be converted to SAC_FCL_SENSOR_SOURCE_TYPE.
 */
DEH_EXPORT NYCE_STATUS NYCE_API SacFclSensorSourceTypeFromString(const char* string, SAC_FCL_SENSOR_SOURCE_TYPE* pValue);

/**
 *  @brief      Check if value is a valid SAC_FCL_SENSOR_SOURCE_TYPE.
 *
 *  @param[in]  value   The value to check.
 *
 *  @retval     TRUE    value is a valid SAC_FCL_SENSOR_SOURCE_TYPE.
 *  @retval     FALSE   value is not a valid SAC_FCL_SENSOR_SOURCE_TYPE.
 */
DEH_EXPORT BOOL SacFclSensorSourceTypeIsValid(SAC_FCL_SENSOR_SOURCE_TYPE value);


/**
 *  @}
 */
#ifdef __cplusplus
}
#endif

#endif
