/*
 *  BOSCH REXROTH
 *
 *  Copyright (c) Bosch Rexroth AG 2014
 *  Internet: http://www.boschrexroth.com
 *
 *  Product Name:   NYCe4000
 *  Component Name: support
 *  Subsystem Name: deh
 *
 *  THIS FILE IS AUTOMATICALLY GENERATED BY
 *  generate_enum_conversion.py
 *  MANUAL MODIFICATIONS WILL BE OVERWRITTEN!!!
 */
/**
 *  @file
 *  @brief  Enum conversion functions for seq.
 *  
 *  For every enum in the seq subsystem the following type to string conversion functions exist:
 *  - "<TYPE>ToString(TYPE)"            Convert the given value of "<TYPE>" to its exact string representation.
 *  - "<TYPE>ToUserString(TYPE)"        Convert the given value of "<TYPE>" to a human readable string.
 *  - "<TYPE>ToDescription(TYPE)"       Convert the given value of "<TYPE>" to a descriptive string.
 *  - "<TYPE>FromString(string, TYPE)"  Convert the given string to value of "<TYPE>".
 *  - "<TYPE>IsValid(TYPE)"             Checks if the given value of "<TYPE>" is valid.
 */

#ifndef __SEQENUMS_H__
#define __SEQENUMS_H__

#include "seqapi.h"

#ifndef DEH_EXPORT
    #ifdef WIN32
        #define DEH_EXPORT __declspec(dllimport)
    #else
        #define DEH_EXPORT
    #endif
#endif

#ifdef __cplusplus
extern "C" {
#endif
/**
 *  @addtogroup seq_conversion
 *  @{
 */

//  SEQ_STATE Conversion routines

/**
 *  @brief      Convert type SEQ_STATE to the exact string representation.
 *
 *  @param[in]  value   The value to convert.
 *
 *  @return     The string representation of value.
 */
DEH_EXPORT const char* NYCE_API SeqStateToString(SEQ_STATE value);

/**
 *  @brief      Convert type SEQ_STATE to a human readable string.
 *
 *  @param[in]  value   The value to convert.
 *
 *  @return     The human readable string representation of value.
 */
DEH_EXPORT const char* NYCE_API SeqStateToUserString(SEQ_STATE value);

/**
 *  @brief      Convert type SEQ_STATE to a descriptive string.
 *
 *  @param[in]  value   The value to convert.
 *
 *  @return     The description of value.
 */
DEH_EXPORT const char* NYCE_API SeqStateToDescription(SEQ_STATE value);

/**
 *  @brief      Convert the given string to an SEQ_STATE.
 *
 *  @param[in]  string  The string to convert.
 *  @param[out] pValue  The enum value of string.
 *
 *  @retval     NYCE_OK                     string is successfully converted to a valid SEQ_STATE.
 *  @retval     SEQ_ERR_INVALID_PARAMETER   string or pValue is NULL.
 *  @retval     SEQ_ERR_UNKNOWN_ENUM_STRING string could not be converted to SEQ_STATE.
 */
DEH_EXPORT NYCE_STATUS NYCE_API SeqStateFromString(const char* string, SEQ_STATE* pValue);

/**
 *  @brief      Check if value is a valid SEQ_STATE.
 *
 *  @param[in]  value   The value to check.
 *
 *  @retval     TRUE    value is a valid SEQ_STATE.
 *  @retval     FALSE   value is not a valid SEQ_STATE.
 */
DEH_EXPORT BOOL SeqStateIsValid(SEQ_STATE value);


/**
 *  @}
 */
#ifdef __cplusplus
}
#endif

#endif
