/*
 *  BOSCH REXROTH
 *
 *  Copyright (c) Bosch Rexroth AG 2014
 *  Internet: http://www.boschrexroth.com
 *
 *  Product Name:   NYCe4000
 *  Component Name: support
 *  Subsystem Name: deh
 *
 *  THIS FILE IS AUTOMATICALLY GENERATED BY
 *  generate_enum_conversion.py
 *  MANUAL MODIFICATIONS WILL BE OVERWRITTEN!!!
 */
/**
 *  @file
 *  @brief  Enum conversion functions for dwn.
 *  
 *  For every enum in the dwn subsystem the following type to string conversion functions exist:
 *  - "<TYPE>ToString(TYPE)"            Convert the given value of "<TYPE>" to its exact string representation.
 *  - "<TYPE>ToUserString(TYPE)"        Convert the given value of "<TYPE>" to a human readable string.
 *  - "<TYPE>ToDescription(TYPE)"       Convert the given value of "<TYPE>" to a descriptive string.
 *  - "<TYPE>FromString(string, TYPE)"  Convert the given string to value of "<TYPE>".
 *  - "<TYPE>IsValid(TYPE)"             Checks if the given value of "<TYPE>" is valid.
 */

#ifndef __DWNENUMS_H__
#define __DWNENUMS_H__

#include "dwnapi.h"

#ifndef DEH_EXPORT
    #ifdef WIN32
        #define DEH_EXPORT __declspec(dllimport)
    #else
        #define DEH_EXPORT
    #endif
#endif

#ifdef __cplusplus
extern "C" {
#endif
/**
 *  @addtogroup dwn_conversion
 *  @{
 */

//  DWN_FLASH_DATA_TYPE Conversion routines

/**
 *  @brief      Convert type DWN_FLASH_DATA_TYPE to the exact string representation.
 *
 *  @param[in]  value   The value to convert.
 *
 *  @return     The string representation of value.
 */
DEH_EXPORT const char* NYCE_API DwnFlashDataTypeToString(DWN_FLASH_DATA_TYPE value);

/**
 *  @brief      Convert type DWN_FLASH_DATA_TYPE to a human readable string.
 *
 *  @param[in]  value   The value to convert.
 *
 *  @return     The human readable string representation of value.
 */
DEH_EXPORT const char* NYCE_API DwnFlashDataTypeToUserString(DWN_FLASH_DATA_TYPE value);

/**
 *  @brief      Convert type DWN_FLASH_DATA_TYPE to a descriptive string.
 *
 *  @param[in]  value   The value to convert.
 *
 *  @return     The description of value.
 */
DEH_EXPORT const char* NYCE_API DwnFlashDataTypeToDescription(DWN_FLASH_DATA_TYPE value);

/**
 *  @brief      Convert the given string to an DWN_FLASH_DATA_TYPE.
 *
 *  @param[in]  string  The string to convert.
 *  @param[out] pValue  The enum value of string.
 *
 *  @retval     NYCE_OK                     string is successfully converted to a valid DWN_FLASH_DATA_TYPE.
 *  @retval     DWN_ERR_INVALID_PARAMETER   string or pValue is NULL.
 *  @retval     DWN_ERR_UNKNOWN_ENUM_STRING string could not be converted to DWN_FLASH_DATA_TYPE.
 */
DEH_EXPORT NYCE_STATUS NYCE_API DwnFlashDataTypeFromString(const char* string, DWN_FLASH_DATA_TYPE* pValue);

/**
 *  @brief      Check if value is a valid DWN_FLASH_DATA_TYPE.
 *
 *  @param[in]  value   The value to check.
 *
 *  @retval     TRUE    value is a valid DWN_FLASH_DATA_TYPE.
 *  @retval     FALSE   value is not a valid DWN_FLASH_DATA_TYPE.
 */
DEH_EXPORT BOOL DwnFlashDataTypeIsValid(DWN_FLASH_DATA_TYPE value);


//  DWN_UPGRADE_TYPE Conversion routines

/**
 *  @brief      Convert type DWN_UPGRADE_TYPE to the exact string representation.
 *
 *  @param[in]  value   The value to convert.
 *
 *  @return     The string representation of value.
 */
DEH_EXPORT const char* NYCE_API DwnUpgradeTypeToString(DWN_UPGRADE_TYPE value);

/**
 *  @brief      Convert type DWN_UPGRADE_TYPE to a human readable string.
 *
 *  @param[in]  value   The value to convert.
 *
 *  @return     The human readable string representation of value.
 */
DEH_EXPORT const char* NYCE_API DwnUpgradeTypeToUserString(DWN_UPGRADE_TYPE value);

/**
 *  @brief      Convert type DWN_UPGRADE_TYPE to a descriptive string.
 *
 *  @param[in]  value   The value to convert.
 *
 *  @return     The description of value.
 */
DEH_EXPORT const char* NYCE_API DwnUpgradeTypeToDescription(DWN_UPGRADE_TYPE value);

/**
 *  @brief      Convert the given string to an DWN_UPGRADE_TYPE.
 *
 *  @param[in]  string  The string to convert.
 *  @param[out] pValue  The enum value of string.
 *
 *  @retval     NYCE_OK                     string is successfully converted to a valid DWN_UPGRADE_TYPE.
 *  @retval     DWN_ERR_INVALID_PARAMETER   string or pValue is NULL.
 *  @retval     DWN_ERR_UNKNOWN_ENUM_STRING string could not be converted to DWN_UPGRADE_TYPE.
 */
DEH_EXPORT NYCE_STATUS NYCE_API DwnUpgradeTypeFromString(const char* string, DWN_UPGRADE_TYPE* pValue);

/**
 *  @brief      Check if value is a valid DWN_UPGRADE_TYPE.
 *
 *  @param[in]  value   The value to check.
 *
 *  @retval     TRUE    value is a valid DWN_UPGRADE_TYPE.
 *  @retval     FALSE   value is not a valid DWN_UPGRADE_TYPE.
 */
DEH_EXPORT BOOL DwnUpgradeTypeIsValid(DWN_UPGRADE_TYPE value);


/**
 *  @}
 */
#ifdef __cplusplus
}
#endif

#endif
